inherit_from: AICGRender/src/object_gaussian/nerfstudio/configs/base.yaml 
data:
  input_path: input/001/out #输入数据路径
  output_image_path: output/objectdoor/model/ #输出结果路径
  output_mesh_path: output/objectdoor/model/
  scene_name: result
cam:  #intrinsic is different per scene in TUM
  H: 2048 
  W: 2448
  fx: 2726.4277079002723
  fy: 2725.892257658144
  cx: 1220.5523871835899
  cy: 1053.9623314810678
  # crop_edge: 50
  #distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]