inherit_from: nerfstudio/configs/My/base.yaml
data:
 input_path: data/My/fusai_updata/004/out #输入数据路径
 output_image_path: data/My/fusai_updata/output/004/render/ #输出结果路径
 output_mesh_path: data/My/fusai_updata/output/004/mesh/
 scene_name: result
cam:  #intrinsic is different per scene in TUM
  H: 2048 
  W: 2448
  fx: 2725.6023088156153 
  fy: 2724.8178680065503 
  cx: 1259.5927480161056
  cy: 1034.8616327951815
  # crop_edge: 50
  #distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]