inherit_from: nerfstudio/configs/My/base.yaml
data:
  input_path: data/My/fusai_updata/006/out #输入数据路径
  output_image_path: data/My/fusai_updata/output/006/render/ #输出结果路径
  output_mesh_path: data/My/fusai_updata/output/006/mesh/
  scene_name: result
cam:  #intrinsic is different per scene in TUM
  H: 2048 
  W: 2448
  fx: 2722.634039978164
  fy: 2722.86551749805
  cx: 1221.3347750394075
  cy: 1001.3051311769937
  # crop_edge: 50
  #distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]